import type { Metadata } from "next";
import AppProvider from "./AppProvider";
import HeadTags from "./HeadTags";
import StyledComponentsRegistry from "./lib/registry";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeadTags />
        <StyledComponentsRegistry>
          <AppProvider>{children}</AppProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
